apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "all-appsets"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jon4hz/miningcore-devel-configs
    targetRevision: HEAD
    path: ./appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
