apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "all-configs"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jon4hz/miningcore-devel-configs
    targetRevision: HEAD
    path: ./configs
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
