apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    helm:
      releaseName: postgresql
      valueFiles:
        - values.yml
    repoURL: git@github.com:jon4hz/miningcore-devel-configs
    path: ./src/postgresql/
    targetRevision: "HEAD"
  destination:
    server: https://kubernetes.default.svc
    namespace: miningcore
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
