---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: default
spec:
  encryptedData:
    password: AgAuKYyCZOyEHIN9ykt7qTLn6CmwS1tnI64sAvF8EsVcdlL72Qjp8Tdq3LuBhxBiyUcBNM4KY+TbmlAAFYqTTyDRFIUtWR9FH98AHoriS9RS7qtJtCwxjDa8hPKjP9MWvK7BE+ZlASBTh5tAJMCXb2JDRCJvnZ9m8WGHfPgGzXG+XanXjS7l5SqEuHONizK9B5sLVSn6Ig/iSA3aGuYVUuqKS3JflAo5hKjHqI8wr87TUrIGMbaK6qyDIBeovqHzPfG2fKhVETyVr8DKar+lrc/eBEWtX2peyrIvV0gVqnNeg46SxxibbQXM7xTwCg0rFaPuuo3zrJqVanfqz0LqGcjUJJfgEHJ6HGcLctj5DmLGHVB5ItIZE2QFIkx+pQq+X6B7JqnNu6jZeQdBiYnaFXFSTXHfVXzUgvLT0DMKwhg2ZXxy35Iv+16DqQWejdfCmxd7173aYGDt4dO6ArffVh+8Pxor5RFKvSJtxJSv1sMfMA+b/N8CPVUN521xZFTwy/+Mzbh4fPFJ5BIBXBm/uOwQUixSnIKDhOuTjfmG10oMuwUTCvnISJHvksWVQagfxdFZMwZo3tzbbfhQz7r/Tmn7UcQ6JQAKXFZXnU2Ao+bAp/aBB2IJe+IXtvmhHyuMLjMhdT1iH5wtbOnPNbJKES4Zm2K8xDJjAs6DnOI+Wqh/BDWzJTr4scKDS3Jba5HBC5VdVZKIOugVxchZmM2qvdIlZj//sCKJffrqmNFDPLMHaWPHuRbj5MwoyVSjMg==
    username: AgA2xAsp1/iZG20ESMZjeQgcu25N2oa6H/cqgiPr0G9T9CO6bbx0efO2Ke7N0inwjTaGbD/dUlzW9BpFfVuMyW9HHQHsz7/xbnhpKZ3Q/UiVquXVfNC4iwxpkQ+V0o74f39+SRUZmKX+VR7dPuEgRGLnGFAqlzPESBein1nAqjpPQmg/W4gGY/ZhC/eSRE1wys8zlSk7nePuBdU05S88GxLqw73avl5p1Vw0Ghdjn3RaiuYVnHmaAY5mgBUUUjQ4PrZrqu1FH2YebtJ04N+xhj09AKHxS0eziL+J539bBohfUOBNxwOm986Ng9dkwEq86j2vJC5SvHu41eyKOWHh4arwlrpffAgEnQ3coXa9v8hbsekiTNVZlnI6y7BqNM/oba1o/BNKddHMbbvuFrp4VK44Lu3iSXXmYtHI1lhCU2TD4ZvWYgh6jrGdpHNdFPkMtPKLgYHDSayT1qe3xNrCxIJc5PpTl1XBRGRGSqsfzJNNTMJqemePN50R1urm8LbNAjetsNa2sxuTboP3yIig57Wgf2EZOuS8k9ifw46s7vC75p+1xRoMEHHx8aF6U50NIj9VDqclDqxsg0eFh5m+QEdGrED/AuxE3Xv5XVcxdWfrRHM6c0M3l5kI4AnPqF5NPeZ+FlcCraV3diTXp1WRa1aDySmrQ1ujf4P0pIOKHKpG2Xu22ae8R7T0dsoCoXlvowGIN+ysPUEu5HYw
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: default
