---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql
  namespace: miningcore
spec:
  encryptedData:
    password: AgBqhabvDUa1sY47Q+Vi2bQmAn8Pj2ZUAsdwxWkj9ZjCD7tMvjUhA0BzUECo4u/Wfw6zLG1180QUWcw2aVovzzLx2IgFoB9gFhyoxg3vkll2laFlxq0L9jyIGoLoM/jkrCEnGQJoeuf1jFz5jHwi1u/XJOaExuv1GFk3WuvAx5bRz+KlC9XHBr88pTRIHZljOzIsT6E9e6Wh0+N16O5unxn1C6PE8Z69nBjlzkmlPcDV12ia2RqmfNi3XK0trduia7TrirlCduip1qn+RdkHoltnbH9dBLhO96+gAnhpbd8EfwDV8JOzL7oAmN2/S+Gilia1BpJ4jHZLW0skYA5+0yXpviWGU77B6VMMbZUvOj5ODidHRbPPbbxf9m0haWchNqoNy3WPFQCQIKxLwLGA0UtBCFIce6Jjrt5pbH3J42uxTAAMTAFKX6yGpdfCoL2MKagiqHhr5ZbDnPwSFi0loeNnxqkSRT9gy+GNf7i+bQS8ve4dAK8LwWTP2p+9Q6L1vwTgjCuc6DgzgPD4r8naL+WSaMthh+JAZbWGTC6i/1Zfm/5nodsFDUPyavaA0UPpPsiIHljCfYgYuPDAJYNM9rlha24RIr5jcgtsRzSHUEMRxLiN5BoA62Y1NCfU2SIPmtTly1+tAaGYySZ53pBzTguDlB6OdZkJNacg836fd36JclmSyvvwi03PgC+sgKY5z3gelffgBuBl8viaAsaLNt5i+bsq4PInGP2twKQuv7Uw6lRWImOM51+z3SJyPg==
    username: AgBt1z8yjwkRXRfqqUgNc4hWpOy/D0xciw2yTWlA7dKb/dzDSPTfaYeeqkfRQ9TUK2SVIL1opek2/hVImlYTZGoRTSKCWnX3p19lQ0XA71YKVeATVrm+bBT5b5YM1emQaxC6H4MZrI6zHGnXgsljgSlgpfyzkKUCFgkICVaVTeCpBvFVT6obwB4U8n3CceoyG3JSuIsHoloQrdQH4CDYBG6qbw4lOyHO6dSFXml32L6K+D6fefRNLqLufOlHMGUmuNZ0KfMkSrNmkcaBzX5TCWVMMiQU+U22k+U41OOSub+QLxxwc+ETD5WI0eh5XGiGIACP+mqG810lR9iEIhj57ekueXiRlgikTioZ9civXbVJaHF2x4c3wnnAM7PwTNzt3o6jjgwJZI8PQNTCMIansDKvK6LfoVP+SHkUOFpXQ3CeNnsUVIpVgjynaZXq6ulesiuz9CaCmouz9KWFCy17PvJXHL73jkPCx3Ee+b+P29r72EMrtQJsRrNJc+6/926Jz/Pwghhj2hJM+2xg2rOIcKV2s31bdM0DBQBwBN87S9KgWT+GSQ9cV/67uGzb7Z501xoVwvbLsleuwEFMNxYsPA3xJuOoYjjGjc6na8YuNZtbW/ftma1hn0t6DzWzNRVfDAs7lTVqoYXg8rZ1CtdFA5jbM8lM39ROm+U0ICt1ZKYbR2ZGqGQOs1VEemK/P4MA0fDFzkPfsZFHQdDT
  template:
    metadata:
      creationTimestamp: null
      name: postgresql
      namespace: miningcore
