---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: default
spec:
  encryptedData:
    password: AgChv9y91KSkQUXZBb+xi0WtonU6aulDC46+QSasIFdZI4siLPqDApMmx5aK2aAw4klJ6vghklsgmrMHcLV4f5BJRxmXQJ7IFJ/swcsNMgRiGc94S7j6ZMoxOMW2E1M2pEROt9K54n2KlxcdrbGPX/4oY8CVXbXTWeAbq1OaQIirLaU95DF5SjoI5/PMk4SoQrugGU+kn+lzwwM9ZvdDXsvRZsvzfbIHp2q0RR8ghH/vr+NvCD7u5H0R9yUD7b/78pGrszj2MlhlS1zs5SfGSgW4G3EJVhLQ/9E6qlUqrNBu8PaoKIrpu3luHMuPCPB7MzAR8XS9s3syys0f9X6L1BO1GsqC8h/G05ryMtNiW0ZMIzXVY+3Zp0fTFkAWew8K4KZ0xt+tCxc/HYYGST2oz1wtmlAhga3E1N7yCHQiZ9ANhecdaCATfj97EKWn7zj4nPA/UQqnafQ0LUDhD1qYPh9ejaPeHtfCfmKv1isbxNW41vLqkwgPGkMK/A/GNuhZduoTdhl2X6GCTPLD+9ZfawBabeH7OMShoSpFIxEj7u+5MRLIPS3afMay+FwqCItP09/Ta0lcwTGx8G9nuYvWmseqLH2AAL0uv85PRX9g3XfD6X1pAg9ISkTkbnoYlCPIoXGlBuvGlQNS+WIM2DwkW99Mvv4K2bfhTdb/hw+RyIORkIZoiq9ktubZehV9f+DkJD03q5PMMWtlkluKlsHZIzFd7giu/F5ZkV09XWWwdZyz7bGWt0kVFFj4quu7tg==
    username: AgCau27bQd3EygPM/ny3y2z0obomH1i8vX9RjmmT1rUu9xdP1b5AdVe7qMzFkeNVTMxfNhEgpNudXhqa93fueHfw13Fnr+NAVgP/wn7XOJoIA7mG3NTNj/mBfksGnrVDwH3ZtqWpukq6R7FlQB+OTBdmOCYwAB7arthj6GJ19kWNJXN+6PrqS4TC2zN5Hi4+NcoypVSGW+aJhTTu0NsndC/0AiyemOW+MlI4KE52ISxqT1PTTdNdUeqWX0I2Zs2UREiaQum8EAPUw46qdn8JP8+PPxk9MLJCRXn+cfCjchX5cG1In877/EL4lVZy8PzSo13uu5Vz6IvUEXnYGe4Vl6NdMtJm79w5QVlCp9/cviPs2iUxjNyfixWGPjKiERLZHaQ2k51ao51zCeVPzWU/Y5pCTYnHZdrm+M9WTeOwU8tysJ4G/rJUM9EZzdsVYQhFRGW1b26m4QrBml2HCCkBnSYj21TP8Zv/zfQt57zT9dEkZ7BiR2ojXSpeBTCp9gwinviSjn8cN6Bu59aVh/awyr5txL1oYtOSH7pjtcWXgCKERg3wyD61U2HxWvx4JqxgikkSLzUKIR+O34CRcnBx8MbHiXx4+parX0GKcoALsx2K2Ucn8yGOuf4Q2r7xx4k7ZOTsRt+3dNLTza/5s7zKZ7rn+NdykIXaaVdgghE2HfkV6LlR099jtlrn0oezkLwY/9aQyj9nGXwApmXQ
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: default
